server:
  port: 8080

# 设置javamelody监控登录的用户名密码 地址 http://localhost:8080/monitoring
javamelody:
  enabled: true
  init-parameters:
    authorized-users: admin:123456
    monitoring-path: /monitoring


spring:
  jta.en
  datasource:
    dynamic:
      primary: db1
      strict: false
      datasource:
        db1:
          driver-class-name: com.mysql.jdbc.Driver
          schema: classpath:db/db1-schema-mysql.sql
          data: classpath:db/db1-data-mysql.sql
          url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
          username: root
          password: root
        db2:
          driver-class-name: com.mysql.jdbc.Driver
          schema: classpath:db/db2-schema-mysql.sql
          data: classpath:db/db2-data-mysql.sql
          url: jdbc:mysql://localhost:3306/db2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
          username: root
          password: root
    initialization-mode: never


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
